...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -478,6 +478,79 @@ NR!=1{
 }
 # EndSection
 
+# Section: Instance management.
+
+# TODO: We could use list to replace this facility.
+# ___x_cmd_instance_add class object
+___x_cmd_instance_new(){
+    local name="${2:?Provide object name}"
+    name="${name#?}"
+    eval "
+function $name {
+    $1 $2 \"\$@\"
+}
+"
+}
+
+___x_cmd_instance_del(){
+    local name="${2:?Provide object name}"
+    # TODO:
+    if [ $# -gt 2 ];then
+        eval "$@"
+    fi
+    name="${name#?}"
+    if command -v "$name" 1>/dev/null 2>&2; then
+        unset "$name"
+    else
+        printf "%s\n" "Instance not found: $O" >&2
+        return 1
+    fi
+}
+
+___x_cmd_instance_has(){
+    local class="${1:?Provide class name}"
+    local object="${2:?Provide object name}"
+    local name="___X_CMD_INSTANCE_$class"
+    eval "[ \"\$$name\" != \"\${$name#*@\${object}-*}\" ]"
+}
+
+___x_cmd_instance_add(){
+    local class="${1:?Provide class name}"
+    local object="${2:?Provide object name}"
+    local name="___X_CMD_INSTANCE_$class"
+    if ! eval "[ \"\$$name\" != \"\${$name#*@\${object}-*}\" ]"; then
+        eval "$name=\"\${$name}@\${object}-\""
+    else
+        printf "%s\n" "Object already enlisted." >&2
+        return 1
+    fi
+}
+
+# ___x_cmd_instance_rm class object
+# shellcheck disable=SC2034
+___x_cmd_instance_rm(){
+    local class="${1:?Provide class name}"
+    local object="${2:?Provide object name}"
+    local name="___X_CMD_INSTANCE_$class"
+    eval "$name=\"\${$name%@\${object}-*}\${$name##*@\${object}-}\""
+}
+
+# ___x_cmd_instance_rm class
+___x_cmd_instance_list(){
+    local class="${1:?Provide class name}"
+    local name="___X_CMD_INSTANCE_$class"
+    eval "[ -z \"\${$name}\" ]" && return
+    eval printf \"%s\" "\"\${$name}\"" | tr "-" "\n" | tr -d @
+}
+
+___x_cmd_instance_clear(){
+    local class="${1:?Provide class name}"
+    local name="___X_CMD_INSTANCE_$class"
+    eval "$name="
+}
+
+# EndSection
+
 # Section: utils: search_path
 ___x_cmd_search_path(){
     local cur="${1:?Provide starting path}"
@@ -597,11 +670,11 @@ ${___X_CMD_WHICH_ONE_RESULT}${___X_CMD_XRC_MODULE_IMPORTED}"
 # EndSection
 
 # Section: xrc_set_main,  which_one, which_one_with_naming
-# RETURN ___X_CMD_WHICH_ONE_RESULT
 ___x_cmd_xrc_set_main(){
     ___X_CMD_XRC_SET_MAIN="${1:?Provide function}"
 }
 
+# RETURN ___X_CMD_WHICH_ONE_NAMING
 ___x_cmd_which_one_with_naming(){
     local RESOURCE_NAME="${1:?Provide resource name for ___x_cmd_which_one_with_naming}"
 
@@ -630,7 +703,7 @@ ___x_cmd_which_one_with_naming(){
     ___x_cmd_which_one "${RESOURCE_NAME#*=}"
 }
 
-
+# RETURN ___X_CMD_WHICH_ONE_RESULT, ___X_CMD_WHICH_ONE_RESOURCE_TYPE
 ___x_cmd_which_one(){
     local RESOURCE_NAME="${1:?Provide resource name for ___x_cmd_which_one}"
 
@@ -706,79 +779,6 @@ ___x_cmd_which_one(){
             return 1
     esac
 }
-# EndSection
-
-# Section: Instance management.
-
-# TODO: We could use list to replace this facility.
-# ___x_cmd_instance_add class object
-___x_cmd_instance_new(){
-    local name="${2:?Provide object name}"
-    name="${name#?}"
-    eval "
-function $name {
-    $1 $2 \"\$@\"
-}
-"
-}
-
-___x_cmd_instance_del(){
-    local name="${2:?Provide object name}"
-    # TODO:
-    if [ $# -gt 2 ];then
-        eval "$@"
-    fi
-    name="${name#?}"
-    if command -v "$name" 1>/dev/null 2>&2; then
-        unset "$name"
-    else
-        printf "%s\n" "Instance not found: $O" >&2
-        return 1
-    fi
-}
-
-___x_cmd_instance_has(){
-    local class="${1:?Provide class name}"
-    local object="${2:?Provide object name}"
-    local name="___X_CMD_INSTANCE_$class"
-    eval "[ \"\$$name\" != \"\${$name#*@\${object}-*}\" ]"
-}
-
-___x_cmd_instance_add(){
-    local class="${1:?Provide class name}"
-    local object="${2:?Provide object name}"
-    local name="___X_CMD_INSTANCE_$class"
-    if ! eval "[ \"\$$name\" != \"\${$name#*@\${object}-*}\" ]"; then
-        eval "$name=\"\${$name}@\${object}-\""
-    else
-        printf "%s\n" "Object already enlisted." >&2
-        return 1
-    fi
-}
-
-# ___x_cmd_instance_rm class object
-# shellcheck disable=SC2034
-___x_cmd_instance_rm(){
-    local class="${1:?Provide class name}"
-    local object="${2:?Provide object name}"
-    local name="___X_CMD_INSTANCE_$class"
-    eval "$name=\"\${$name%@\${object}-*}\${$name##*@\${object}-}\""
-}
-
-# ___x_cmd_instance_rm class
-___x_cmd_instance_list(){
-    local class="${1:?Provide class name}"
-    local name="___X_CMD_INSTANCE_$class"
-    eval "[ -z \"\${$name}\" ]" && return
-    eval printf \"%s\" "\"\${$name}\"" | tr "-" "\n" | tr -d @
-}
-
-___x_cmd_instance_clear(){
-    local class="${1:?Provide class name}"
-    local name="___X_CMD_INSTANCE_$class"
-    eval "$name="
-}
-
 # EndSection
 
 # Section: env
