...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -409,26 +409,53 @@ ___x_cmd_which_one(){
 }
 # EndSection
 
-# Section: Small list for Instance management.
+# Section: Instance management.
 
 # ___x_cmd_instance_add class object
+# ___x_cmd_instance_new dict_make :ali "$@"
+___x_cmd_instance_new(){
+    local name="${2:?Provide object name}"
+    name="${name#?}"
+    eval "
+function $name {
+    $1 $2 \"\$@\"
+}
+" && "$@"
+
+}
+
+___x_cmd_instance_del(){
+    local name="${2:?Provide object name}"
+    eval "$@"
+    name="${name#?}"
+    if command -v $name 1>/dev/null 2>&2; then
+        eval "$@" && unset "$name"
+    else
+        printf "%s\n" "Instance not found: $O" >&2
+        return 1
+    fi
+}
 
 ___x_cmd_instance_has(){
     local class="${1:?Provide class name}"
     local object="${2:?Provide object name}"
     local name="___X_CMD_INSTANCE_$class"
-    eval [ \"\$$name\" != \"${$name#*@\${object}-}\" ]
+    eval [ \"\$$name\" != \"\${$name#*@\${object}-*}\" ]
 }
 
 ___x_cmd_instance_add(){
     local class="${1:?Provide class name}"
     local object="${2:?Provide object name}"
     local name="___X_CMD_INSTANCE_$class"
-    eval "$name=\"\${$name}@\${object}-\""
+    if ! eval [ \"\$$name\" != \"\${$name#*@\${object}-*}\" ]; then
+        eval "$name=\"\${$name}@\${object}-\""
+    else
+        printf "%s\n" "Object already enlisted." >&2
+        return 1
+    fi
 }
 
 # ___x_cmd_instance_rm class object
-
 ___x_cmd_instance_rm(){
     local class="${1:?Provide class name}"
     local object="${2:?Provide object name}"
