...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -533,106 +533,6 @@ ___x_cmd_readlink_recursive(){
 
 # EndSection
 
-# Section: main entrance helper: cat, source_file
-___x_cmd_xrc_cat(){
-    while [ $# -ne 0 ]; do
-        local ___X_CMD_LOCAL_XRCPATH="$1";   shift
-
-        if ! ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one "$___X_CMD_LOCAL_XRCPATH"; then
-            printf "ERROR: Interrupted because resource not found. %s \n" "$___X_CMD_LOCAL_XRCPATH" >&2
-            return 1
-        fi
-
-        cat "$___X_CMD_WHICH_ONE_RESULT"
-    done
-}
-
-___X_CMD_XRC_MODULE_IMPORTED="
-"
-
-___x_cmd_xrc_source_file(){
-    local ___X_CMD_WHICH_ONE_NAMING
-    local ___X_CMD_WHICH_ONE_RESULT
-    local ___X_CMD_LOCAL_XRCPATH
-
-    while [ $# -ne 0 ]; do
-        ___X_CMD_LOCAL_XRCPATH="$1";   shift
-
-        if ! ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one_with_naming "$___X_CMD_LOCAL_XRCPATH"; then
-            printf "ERROR: Interrupted because resource not found. %s \n" "$___X_CMD_LOCAL_XRCPATH" >&2
-            printf "%s\n" "return 1"
-            return 1
-        fi
-
-        # Ask whether using http or outside resource.
-        if [ "$___X_CMD_WHICH_ONE_RESOURCE_TYPE" = http ] && [ -z "$NOWARN" ]; then
-
-            # We should do it before ___x_cmd_which_one
-            printf "Sourcing script from untrusted location: %s\n" "$___X_CMD_LOCAL_XRCPATH"
-            cat >&2 <<A
-SECURITY WARNING! Sourcing script from untrusted location: $___X_CMD_WHICH_ONE_RESULT
-If you confirm this script is secure and want to skip this warning for some purpose, use the following code.
-> NOWARN=1 xrc "$___X_CMD_LOCAL_XRCPATH"
-A
-            printf "Input yes to continue. Otherwise exit > " >&2
-            local ___X_CMD_LOCAL_INPUT
-            read -r ___X_CMD_LOCAL_INPUT
-
-            if [ "$___X_CMD_LOCAL_INPUT" != "yes" ]; then
-                rm "$___X_CMD_WHICH_ONE_RESULT"
-                printf "%s\n" "Exit because of a non yes output received: $___X_CMD_LOCAL_INPUT" >&2
-                printf "%s\n" "return 1"
-                return 1
-            fi
-        fi
-
-        ___x_cmd_xrc_source_file_main "$___X_CMD_WHICH_ONE_RESULT"
-    done
-}
-
-___x_cmd_xrc_source_file_main(){
-    ___X_CMD_WHICH_ONE_RESULT="${1:?Provide exact file}"
-
-    if [ -z "$___X_CMD_XRC_RELOAD" ]; then
-        if [ "${___X_CMD_XRC_MODULE_IMPORTED#*
-"$___X_CMD_WHICH_ONE_RESULT"
-*}" != "${___X_CMD_XRC_MODULE_IMPORTED}" ]; then
-            ___X_CMD_XRC_SET_MAIN="$(___x_cmd_ldict_get ___X_CMD_XRC_SET_MAIN_DICT "${___X_CMD_WHICH_ONE_RESULT}")"
-
-            if [ -n "$___X_CMD_WHICH_ONE_NAMING" ] && [ "$___X_CMD_WHICH_ONE_NAMING" != "$___X_CMD_XRC_SET_MAIN" ]; then
-                eval "
-                $___X_CMD_WHICH_ONE_NAMING(){
-                    \"$___X_CMD_XRC_SET_MAIN\" \"\$@\"
-                }"
-            fi
-            ___X_CMD_XRC_SET_MAIN=
-            return    # exited already. skip
-        fi
-    fi
-
-    ___X_CMD_XRC_MODULE_IMPORTED="
-${___X_CMD_WHICH_ONE_RESULT}${___X_CMD_XRC_MODULE_IMPORTED}"
-
-    ___X_CMD_XRC_SET_MAIN=
-    ___x_cmd_source "$___X_CMD_WHICH_ONE_RESULT"
-
-    if [ -n "$___X_CMD_XRC_SET_MAIN" ]; then
-        ___x_cmd_ldict_put ___X_CMD_XRC_SET_MAIN_DICT "${___X_CMD_WHICH_ONE_RESULT}" "${___X_CMD_XRC_SET_MAIN}"
-        # TODO: rename module
-        if [ -n "$___X_CMD_WHICH_ONE_NAMING" ] && [ "$___X_CMD_WHICH_ONE_NAMING" != "$___X_CMD_XRC_SET_MAIN" ]; then
-            eval "
-            $___X_CMD_WHICH_ONE_NAMING(){
-                \"$___X_CMD_XRC_SET_MAIN\" \"\$@\"
-            }"
-        fi
-
-        ___X_CMD_XRC_SET_MAIN=
-    fi
-}
-
-
-# EndSection
-
 # Section: main entrance helper: xrc_set_main, which_one, which_one_with_naming
 ___x_cmd_xrc_set_main(){
     ___X_CMD_XRC_SET_MAIN="${1:?Provide function}"
@@ -743,6 +643,106 @@ ___x_cmd_which_one(){
             return 1
     esac
 }
+# EndSection
+
+# Section: main entrance helper: cat, source_file
+___x_cmd_xrc_cat(){
+    while [ $# -ne 0 ]; do
+        local ___X_CMD_LOCAL_XRCPATH="$1";   shift
+
+        if ! ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one "$___X_CMD_LOCAL_XRCPATH"; then
+            printf "ERROR: Interrupted because resource not found. %s \n" "$___X_CMD_LOCAL_XRCPATH" >&2
+            return 1
+        fi
+
+        cat "$___X_CMD_WHICH_ONE_RESULT"
+    done
+}
+
+___X_CMD_XRC_MODULE_IMPORTED="
+"
+
+___x_cmd_xrc_source_file(){
+    local ___X_CMD_WHICH_ONE_NAMING
+    local ___X_CMD_WHICH_ONE_RESULT
+    local ___X_CMD_LOCAL_XRCPATH
+
+    while [ $# -ne 0 ]; do
+        ___X_CMD_LOCAL_XRCPATH="$1";   shift
+
+        if ! ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one_with_naming "$___X_CMD_LOCAL_XRCPATH"; then
+            printf "ERROR: Interrupted because resource not found. %s \n" "$___X_CMD_LOCAL_XRCPATH" >&2
+            printf "%s\n" "return 1"
+            return 1
+        fi
+
+        # Ask whether using http or outside resource.
+        if [ "$___X_CMD_WHICH_ONE_RESOURCE_TYPE" = http ] && [ -z "$NOWARN" ]; then
+
+            # We should do it before ___x_cmd_which_one
+            printf "Sourcing script from untrusted location: %s\n" "$___X_CMD_LOCAL_XRCPATH"
+            cat >&2 <<A
+SECURITY WARNING! Sourcing script from untrusted location: $___X_CMD_WHICH_ONE_RESULT
+If you confirm this script is secure and want to skip this warning for some purpose, use the following code.
+> NOWARN=1 xrc "$___X_CMD_LOCAL_XRCPATH"
+A
+            printf "Input yes to continue. Otherwise exit > " >&2
+            local ___X_CMD_LOCAL_INPUT
+            read -r ___X_CMD_LOCAL_INPUT
+
+            if [ "$___X_CMD_LOCAL_INPUT" != "yes" ]; then
+                rm "$___X_CMD_WHICH_ONE_RESULT"
+                printf "%s\n" "Exit because of a non yes output received: $___X_CMD_LOCAL_INPUT" >&2
+                printf "%s\n" "return 1"
+                return 1
+            fi
+        fi
+
+        ___x_cmd_xrc_source_file_main "$___X_CMD_WHICH_ONE_RESULT"
+    done
+}
+
+___x_cmd_xrc_source_file_main(){
+    ___X_CMD_WHICH_ONE_RESULT="${1:?Provide exact file}"
+
+    if [ -z "$___X_CMD_XRC_RELOAD" ]; then
+        if [ "${___X_CMD_XRC_MODULE_IMPORTED#*
+"$___X_CMD_WHICH_ONE_RESULT"
+*}" != "${___X_CMD_XRC_MODULE_IMPORTED}" ]; then
+            ___X_CMD_XRC_SET_MAIN="$(___x_cmd_ldict_get ___X_CMD_XRC_SET_MAIN_DICT "${___X_CMD_WHICH_ONE_RESULT}")"
+
+            if [ -n "$___X_CMD_WHICH_ONE_NAMING" ] && [ "$___X_CMD_WHICH_ONE_NAMING" != "$___X_CMD_XRC_SET_MAIN" ]; then
+                eval "
+                $___X_CMD_WHICH_ONE_NAMING(){
+                    \"$___X_CMD_XRC_SET_MAIN\" \"\$@\"
+                }"
+            fi
+            ___X_CMD_XRC_SET_MAIN=
+            return    # exited already. skip
+        fi
+    fi
+
+    ___X_CMD_XRC_MODULE_IMPORTED="
+${___X_CMD_WHICH_ONE_RESULT}${___X_CMD_XRC_MODULE_IMPORTED}"
+
+    ___X_CMD_XRC_SET_MAIN=
+    ___x_cmd_source "$___X_CMD_WHICH_ONE_RESULT"
+
+    if [ -n "$___X_CMD_XRC_SET_MAIN" ]; then
+        ___x_cmd_ldict_put ___X_CMD_XRC_SET_MAIN_DICT "${___X_CMD_WHICH_ONE_RESULT}" "${___X_CMD_XRC_SET_MAIN}"
+        # TODO: rename module
+        if [ -n "$___X_CMD_WHICH_ONE_NAMING" ] && [ "$___X_CMD_WHICH_ONE_NAMING" != "$___X_CMD_XRC_SET_MAIN" ]; then
+            eval "
+            $___X_CMD_WHICH_ONE_NAMING(){
+                \"$___X_CMD_XRC_SET_MAIN\" \"\$@\"
+            }"
+        fi
+
+        ___X_CMD_XRC_SET_MAIN=
+    fi
+}
+
+
 # EndSection
 
 # Section: main entrance
