...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -3,9 +3,9 @@
 # Section: Requirement & Initialize
 if curl --version 1>/dev/null 2>&1; then
     [ -n "$KSH_VERSION" ] && alias local=typeset
-    ___xcmd_http_get(){
+    ___x_cmd_http_get(){
         # Other solution: --speed-time 5 --speed-limit 10, disconnect if less than 10kb, and last for 5 seconds.
-        xrc_log debug "curl ${XRC_MAX_TIME+--max-time $XRC_MAX_TIME} --fail ${1:?Provide target URL}"
+        ___xrc_log debug "curl ${XRC_MAX_TIME+--max-time $XRC_MAX_TIME} --fail ${1:?Provide target URL}"
         eval curl ${XRC_MAX_TIME+--max-time $XRC_MAX_TIME} --fail "\"\${1}\"" 2>/dev/null
         local code=$?
         # TODO: figure out a way to distinguish timeout or network failure
@@ -17,22 +17,22 @@ else
     return 1 || exit 1
 fi
 
-xrc_log(){
+___xrc_log(){
     local level="$1"; shift
     [ "$level" = debug ] && return
     printf "[%s]: %s\n" "$level" "$@"
 }
 
-X_CMD_SRC_SHELL="sh"
-if      [ -n "$ZSH_VERSION" ];  then    X_CMD_SRC_SHELL="zsh";  setopt aliases
-elif    [ -n "$BASH_VERSION" ]; then    X_CMD_SRC_SHELL="bash"; shopt -s expand_aliases
-elif    [ -n "$KSH_VERSION" ];  then    X_CMD_SRC_SHELL="ksh"
+___X_CMD_CUR_SHELL="sh"
+if      [ -n "$ZSH_VERSION" ];  then    ___X_CMD_CUR_SHELL="zsh";  setopt aliases
+elif    [ -n "$BASH_VERSION" ]; then    ___X_CMD_CUR_SHELL="bash"; shopt -s expand_aliases
+elif    [ -n "$KSH_VERSION" ];  then    ___X_CMD_CUR_SHELL="ksh"
 fi
 
 TMPDIR=${TMPDIR:-$(dirname "$(mktemp -u)")/}    # It is posix standard. BUT NOT set in some cases.
 
 if [ -z "$___X_CMD_PATH" ]; then
-    xrc_log debug "Setting env ___X_CMD_PATH: $___X_CMD_PATH"
+    ___xrc_log debug "Setting env ___X_CMD_PATH: $___X_CMD_PATH"
     ___X_CMD_PATH="$HOME/.x-cmd"           # boot will be placed in "$HOME/.x-cmd/boot"
     mkdir -p "$___X_CMD_PATH" || return 1 || exit 1
     PATH="$___X_CMD_PATH/.bin:$PATH"
@@ -41,11 +41,11 @@ fi
 # EndSection
 
 # Section: network & mirror
-___xcmd_curl() {
+___x_cmd_curl() {
     local REDIRECT=/dev/stdout
     if [ -n "$CACHE" ]; then
         if [ -z "$___XRC_UPDATE" ] && [ -f "$CACHE" ]; then
-            xrc_log debug "Function ___xcmd_curl() terminated. Because local cache existed with update flag unset: $CACHE"
+            ___xrc_log debug "Function ___x_cmd_curl() terminated. Because local cache existed with update flag unset: $CACHE"
             return 0
         fi
         # First make sure it works before webservice. Fail fast.
@@ -53,14 +53,14 @@ ___xcmd_curl() {
         REDIRECT="$TMPDIR/x-bash-temp-download.$RANDOM"
     fi
 
-    if ___xcmd_http_get "$1" 1>"$REDIRECT"; then
+    if ___x_cmd_http_get "$1" 1>"$REDIRECT"; then
         if [ -n "$CACHE" ]; then
-            xrc_log debug "Copy the temp file to CACHE file: $CACHE"
+            ___xrc_log debug "Copy the temp file to CACHE file: $CACHE"
             mv "$REDIRECT" "$CACHE"
         fi
     else
         local code=$?
-        xrc_log debug "___xcmd_http_get $1 return code: $code. Fail to retrieve file from: $1"
+        ___xrc_log debug "___x_cmd_http_get $1 return code: $code. Fail to retrieve file from: $1"
         [ -n "$CACHE" ] && rm -f "$REDIRECT"    # In centos, file in "$REDIRECT" is write protected.
         return $code
     fi
@@ -109,7 +109,7 @@ SUBCOMMAND:
             ;;
         c|cat)
             if [ $# -gt 0 ]; then
-                eval "$(t="cat" ___xcmd_xrc_source_file_list_code "$@")"
+                eval "$(t="cat" ___x_cmd_xrc_source_file_list_code "$@")"
                 return
             fi
             cat >&2 <<A
@@ -120,7 +120,7 @@ A
             return 1;;
         w|which)
             if [ $# -gt 0 ]; then
-                eval "$(t="printf" ___xcmd_xrc_source_file_list_code "$@")"
+                eval "$(t="printf" ___x_cmd_xrc_source_file_list_code "$@")"
                 return
             fi
             cat >&2 <<A
@@ -144,21 +144,21 @@ A
                 RELOAD=1 xrc xrc; return
             fi
             local ___XRC_RELOAD=1
-            eval "$(t="." ___xcmd_xrc_source_file_list_code "$@")" ;;
+            eval "$(t="." ___x_cmd_xrc_source_file_list_code "$@")" ;;
         *)
-            eval "$(t="." ___xcmd_xrc_source_file_list_code "$@")"
+            eval "$(t="." ___x_cmd_xrc_source_file_list_code "$@")"
     esac
 }
 
 # Section: xrc helper function
-___xcmd_xrc_source_file_list_code(){
+___x_cmd_xrc_source_file_list_code(){
     local code=""
     local file
     local exec=${t:-.}
     while [ $# -ne 0 ]; do
-        # What if the ___xcmd_which_one contains '"'
+        # What if the ___x_cmd_which_one contains '"'
         local XRC_MAX_TIME=3        # Consider one file is less than 100KB, bandwidth at least 35KB/s.
-        if ! file="$(___xcmd_which_one "$1")"; then
+        if ! file="$(___x_cmd_which_one "$1")"; then
             echo "return 1"
             return 0
         fi
@@ -201,7 +201,7 @@ $file\""
     printf "%s\n" "$code"
 }
 
-___xcmd_curl_gitx(){   # Simple strategy
+___x_cmd_curl_gitx(){   # Simple strategy
     local repo="${1:?Provide reponame}"
     local mod="${2:?Provide location like str}"
     local mod_repo=${mod%%/*}
@@ -218,12 +218,12 @@ ___xcmd_curl_gitx(){   # Simple strategy
     while read -r mirror; do
         # shellcheck disable=SC2059
         urlpath="$(printf "$mirror" "$repo" "$mod_repo" "$mod_subpath")"
-        xrc_log debug "Trying: $urlpath"
-        ___xcmd_curl "$urlpath"
+        ___xrc_log debug "Trying: $urlpath"
+        ___x_cmd_curl "$urlpath"
 
         case $? in
             0)  if [ "$lineno" -ne 1 ]; then
-                    xrc_log debug "Current default mirror is $mirror"
+                    ___xrc_log debug "Current default mirror is $mirror"
                     xrc mirror "$mirror" "$(echo "$mirror_list" | awk "NR!=$lineno{ print \$0 }" )"
 
                     # Set CHINA_NET FLAG
@@ -233,9 +233,9 @@ ___xcmd_curl_gitx(){   # Simple strategy
                     esac
                 fi
                 return 0;;
-            4)  xrc_log debug "Network unavailable."
+            4)  ___xrc_log debug "Network unavailable."
                 return 4;;
-            *)  xrc_log debug "Mirror is down: $urlpath"
+            *)  ___xrc_log debug "Mirror is down: $urlpath"
         esac
         lineno=$((lineno+1))
     done <<A
@@ -244,7 +244,7 @@ A
     return 1
 }
 
-___xcmd_search_path(){
+___x_cmd_search_path(){
     local cur="${1:?Provide starting path}"
 
     cur="$(cd "$cur" 1>/dev/null 2>&1 && pwd)"
@@ -260,24 +260,24 @@ ___xcmd_search_path(){
     return 1
 }
 
-___xcmd_which_one(){
+___x_cmd_which_one(){
     local RESOURCE_NAME=${1:?Provide resource name}
 
     local TGT
     ___X_CMD_UNTRUSTED_RESOURCE=0
     case "$RESOURCE_NAME" in
         /*)
-            xrc_log debug "Resource recognized as local file: $RESOURCE_NAME"
+            ___xrc_log debug "Resource recognized as local file: $RESOURCE_NAME"
             printf "%s" "$RESOURCE_NAME"
             return 0
             ;;
         http://*|https://*)
             ___X_CMD_UNTRUSTED_RESOURCE=1
-            xrc_log debug "Resource recognized as http resource: $RESOURCE_NAME"
+            ___xrc_log debug "Resource recognized as http resource: $RESOURCE_NAME"
 
             TGT="$___X_CMD_PATH/.http_resource/BASE64-URL-$(printf "%s" "$RESOURCE_NAME" | base64 | tr -d '\r\n')"
-            if ! CACHE="$TGT" ___xcmd_curl "$RESOURCE_NAME"; then
-                xrc_log debug "ERROR: Fail to load http resource due to network error or other: $RESOURCE_NAME "
+            if ! CACHE="$TGT" ___x_cmd_curl "$RESOURCE_NAME"; then
+                ___xrc_log debug "ERROR: Fail to load http resource due to network error or other: $RESOURCE_NAME "
                 return 1
             else
                 printf "%s" "$TGT"
@@ -288,30 +288,30 @@ ___xcmd_which_one(){
             ___xcmd_hub_file_which "$RESOURCE_NAME"     # Will set ___X_CMD_UNTRUSTED_RESOURCE=1 if from unknow source
             ;;
         ./*|../*)
-            xrc_log debug "Resource recognized as local file with relative path: $RESOURCE_NAME"
+            ___xrc_log debug "Resource recognized as local file with relative path: $RESOURCE_NAME"
             local tmp
             if tmp="$(cd "$(dirname "$RESOURCE_NAME")" || exit 1; pwd)"; then
                 printf "%s" "$tmp/$(basename "$RESOURCE_NAME")"
                 return 0
             else
-                xrc_log warn "Local file not exists: $RESOURCE_NAME"
+                ___xrc_log warn "Local file not exists: $RESOURCE_NAME"
                 return 1
             fi
             ;;
         *)
             [ -f "$RESOURCE_NAME" ] && printf "%s" "$RESOURCE_NAME" && return      # local file
 
-            if TGT="$(___xcmd_search_path . ".x-cmd/$RESOURCE_NAME")"; then
+            if TGT="$(___x_cmd_search_path . ".x-cmd/$RESOURCE_NAME")"; then
                 printf "%s" "$TGT/.x-cmd/$RESOURCE_NAME"
                 return                   # .x-cmd
             fi
 
             # x-bash module
-            xrc_log debug "Resource recognized as x-bash module: $RESOURCE_NAME"
+            ___xrc_log debug "Resource recognized as x-bash module: $RESOURCE_NAME"
             local module="$RESOURCE_NAME"
             if [ "${RESOURCE_NAME#*/}" = "$RESOURCE_NAME" ] ; then
                 module="$module/latest"         # If it is short alias like str (short for str/latest)
-                xrc_log debug "Version suffix unavailable. Using \"latest\" by default: $module"
+                ___xrc_log debug "Version suffix unavailable. Using \"latest\" by default: $module"
             fi
             TGT="$___X_CMD_PATH/$module"
 
@@ -320,9 +320,9 @@ ___xcmd_which_one(){
                 return
             fi
 
-            xrc_log info "Dowloading resource=$RESOURCE_NAME to local cache: $TGT"
-            if ! CACHE="$TGT" ___xcmd_curl_gitx "x-bash" "$module"; then
-                xrc_log warn "ERROR: Fail to load module due to network error or other: $RESOURCE_NAME"
+            ___xrc_log info "Dowloading resource=$RESOURCE_NAME to local cache: $TGT"
+            if ! CACHE="$TGT" ___x_cmd_curl_gitx "x-bash" "$module"; then
+                ___xrc_log warn "ERROR: Fail to load module due to network error or other: $RESOURCE_NAME"
                 return 1
             fi
             printf "%s" "$TGT"
@@ -337,10 +337,10 @@ case "$(xrc mirror|head -n1)" in
 esac
 
 [ -f "$(xrc initrc which)" ] && . "$(xrc initrc which)"
-x(){    unset -f x; xrc reload xcmd/v0 && x ${1:+"$@"};    }
+x(){    unset -f x; xrc reload x/v0 && x ${1:+"$@"};    }
 
 if [ -z "$XRC_NO_ADVISE" ] && [ -n "${BASH_VERSION}${ZSH_VERSION}" ] && [ "${-#*i}" != "$-" ]; then
-    xrc_log debug "Using module advise for completion."
+    ___xrc_log debug "Using module advise for completion."
     xrc advise/v0
     advise init xrc - <<A
 {
