...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -1,7 +1,7 @@
 # shellcheck shell=sh disable=SC2039,SC1090,SC3043,SC2263
 
-# Section: Requirement & Initialize
 if curl --version 1>/dev/null 2>&1; then
+# Section: Requirement & Initialize
     [ -n "$KSH_VERSION" ] && alias local=typeset
     ___x_cmd_http_get(){
         # Other solution: --speed-time 5 --speed-limit 10, disconnect if less than 10kb, and last for 5 seconds.
@@ -12,10 +12,6 @@ if curl --version 1>/dev/null 2>&1; then
         # [ $code -eq 28 ] && return 4
         return $code
     }
-else
-    printf "boot[ERR]: Cannot found curl or wget for web resource downloader." >&2
-    return 1 || exit 1
-fi
 
 ___xrc_log(){
     local level="$1"; shift
@@ -88,6 +84,7 @@ ___x_cmd_mirror(){
 }
 # EndSection
 
+# Section: main entrance
 xrc(){
     [ $# -eq 0 ] && set -- "help"
     local subcmd="$1";  shift
@@ -148,6 +145,7 @@ A
             eval "$(t="." ___x_cmd_xrc_source_file_list_code "$@")"
     esac
 }
+# EndSection
 
 # Section: xrc helper function
 ___x_cmd_xrc_source_file_list_code(){
@@ -363,3 +361,10 @@ if [ -z "$XRC_NO_ADVISE" ] && [ -n "${BASH_VERSION}${ZSH_VERSION}" ] && [ "${-#*
 A
 fi
 # EndSection
+
+else
+    printf "boot[ERR]: Cannot found curl or wget for web resource downloader." >&2
+    return 1 2>/dev/null
+    ( return 1 )                # Provide error code 1
+    # return 1 || exit 1
+fi
